import { FormControlLabel, FormGroup } from '@mui/material'
import { Box } from '@mui/system'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { MaterialUISwitch } from "../components/Switch"
import { Footer } from "../components/Footer"

export default function Home() {
  const [ theme, setTheme ] = useState('day')
  
  const main = {
    dark: "#292C35",
    light: "#F1F1F1",
    label: "#111"
  }

  const changeTheme = () => {
    if(theme==='day') {
      console.log(theme)
      return setTheme('dark')
    }else {
      console.log(theme)
      return setTheme('day')
    }
  }

  useEffect(() => {
    changeTheme()
  },[])


  return (
    <>
    <Head>
      <title>Theme Switcher</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box
      sx={{
        width: "100vw",
        height: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: (theme==='day') ? main.dark : main.light,
        color:  (theme==='day') ? main.light : main.dark,
      }}
    >
    <FormGroup>
      <FormControlLabel
        onClick={() => changeTheme()}
        control={<MaterialUISwitch />}
        label="Change Theme"
      />
    </FormGroup>
    </Box>
    <Box
      sx={{
        width: "100%",
        height: "60px",
        position: "fixed",
        bottom: 0
      }}
    >
      <Footer color={(theme==='day') ? main.light : main.dark} />
    </Box>
    </>
  )
}
